import {
  BaseEntity,
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
} from 'typeorm'
import { CourseModel } from '../../../course/course.entity'
import { Exclude } from 'class-transformer'
import { EmbeddableQuestionFeedbackModel } from './embeddable-question-feedback.entity'
import { EmbeddableAssignmentQuestionModel } from '../assignment/embeddable-assignment-question.entity'

@Entity('embeddable_question_model')
export class EmbeddableQuestionModel extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn({ type: 'timestamptz', nullable: false })
  createdAt: Date;

  @Column({ type: 'timestamptz', nullable: true })
  availableFrom?: Date;

  @Column({ type: 'timestamptz', nullable: true })
  availableUntil?: Date;

  @ManyToOne(() => CourseModel, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'courseId' })
  @Exclude()
  course: CourseModel;

  @Column()
  courseId: number;

  // professors can name their questions or have an autogenerated name
  @Column({ type: 'text' })
  name: string;

  @Column({ type: 'text' })
  questionText: string;

  // criteria included in the prompt for feedback generation
  @Column({ type: 'text' })
  criteriaText: string;

  // instructions included in the prompt for feedback generation
  @Column({ type: 'text', nullable: true })
  instructions?: string;

  @OneToMany(() => EmbeddableQuestionFeedbackModel, (feedback) => feedback.embeddableQuestion)
  @Exclude()
  submissions: EmbeddableQuestionFeedbackModel[];

  @OneToMany(() => EmbeddableAssignmentQuestionModel, (assignment) => assignment.question)
  assignments: EmbeddableAssignmentQuestionModel[];

  @Column({ type: 'boolean', default: false })
  isWeak: boolean;
}
