export enum SettingsOptions {
  PROFILE = 'PROFILE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  TEAMS_SETTINGS = 'TEAMS_SETTINGS',
  PREFERENCES = 'PREFERENCES',
  EMAIL_NOTIFICATIONS = 'EMAIL_NOTIFICATIONS',
}
