export enum SettingsOptions {
  PROFILE = 'PROFILE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  TEAMS_SETTINGS = 'TEAMS_SETTINGS',
  PREFERENCES = 'PREFERENCES',
  CHATBOT_HISTORY = 'CHATBOT_HISTORY',
  ACCESS_TOKENS = 'ACCESS_TOKENS',
}
