@startuml

skin rose

title "mark question sequence diagram"

actor User as "TA"
participant frontend
participant server
database db

User -> frontend : request queue page
frontend -> server : request queue page
server -> db : request queue data
server <- db : queue data
frontend <- server : queue page
User <- frontend : queue page

=== Relevant stuff ==

== get current queue config ==
frontend -> frontend : check if current session is in progress\n (not null)
alt no current session
    User <- frontend : no session in progress \n please wait
else current session in progress
    frontend -> server : get current queueSession config \n (giving currentQueueSessionId)
    server -> db : get current queueSession config
    server <- db : current queueSession config
    frontend <- server : current queueSession config
    frontend -> frontend : parse config and save in variables
end


'== get all current student progress (TA) ==
'frontend -> server : get all current student progress
'note left : we're choosing to get all students' \n progress since that way we can \n display it on desktop
====


frontend <- server : new task question for "part 2"
frontend -> frontend : renders new task question, needs \n to know what tasks are already done
User <- frontend : sees new task question
frontend --> server : get current task list for \n the student (asynchronous)
server -> db : get current task list for student
server <- db : current task list for student (if any)
frontend <- server : current task list for student
User <- frontend : sees what tasks the \n student has already done
note right : not much time has passed, \n shouldn't really be noticable

User -> frontend : task question looks good, \n mark as done
frontend -> server : mark done task for student for \n "lab 1". 
server -> db : get current task list for student
server <- db : current task list for student (if any)
alt no task list made for student yet
    server -> db : create new task list with \n new task appended
else task list already made
    server -> server : check to see if this is a new task
    alt new task
        server -> db : append onto task list
    else not new task
        server -> db : replace old task item
    end
end
frontend <- server : done
User <- frontend : done


@enduml