@startuml

skin rose

title "create task question sequence diagram"

actor User as "Student"
participant frontend
participant server
database db

User -> frontend : request queue page
frontend -> server : request queue page
server -> db : request queue data
server <- db : queue data
frontend <- server : queue page
User <- frontend : queue page

=== Relevant stuff ==

== get current queue config ==
frontend -> frontend : check if current session is in progress\n (not null)
alt no current session
    User <- frontend : no session in progress \n please wait
else current session in progress
    frontend -> server : get current queueSession config \n (giving currentQueueSessionId)
    server -> db : get current queueSession config
    server <- db : current queueSession config
    frontend <- server : current queueSession config
    frontend -> frontend : parse config and save in variables
end

====


frontend --> server : get task progress \n for the student in this queue for "lab1"
server -> db : get task progress data for "lab1"
server <- db : task progress data for "lab1"
frontend <- server : task progress data for "lab1"

User -> frontend : create task question\n for "part2"
frontend -> server : create task question\n for "part2"
server -> db : create question with "isTaskQuestion" flag\n enabled and text with "Mark "part2""

== Database change triggers update to all clients (push) ==

frontend <- server : updated queue
frontend -> frontend : sees task question, \n parses "part 2" from question text, \n renders the task question based \n on the config 
User <- frontend : sees new task question

@enduml