'use client'

import { API } from '@/app/api'
import { getErrorMessage } from '@/app/utils/generalUtils'
import printQRCode from '@/app/utils/QRCodePrintUtils'
import { CopyOutlined, QrcodeOutlined, ReloadOutlined } from '@ant-design/icons'
import { OrganizationCourseResponse } from '@koh/common'
import { Button, Form, Input, Popconfirm, message } from 'antd'
import { useCallback, useEffect, useState } from 'react'

interface FormValues {
  courseInviteCode: string | null
}

type CourseInviteCodeProps = {
  courseData: OrganizationCourseResponse
  fetchCourseData: () => void
}

const CourseInviteCode: React.FC<CourseInviteCodeProps> = ({
  courseData,
  fetchCourseData,
}) => {
  const [form] = Form.useForm()
  const courseCode = courseData.course?.courseInviteCode
  const isEnabled = courseData.course?.isCourseInviteEnabled ?? false
  const [copyLinkText, setCopyLinkText] = useState('Copy Link')

  const updateCourseInvite = useCallback(
    async (params: {
      inviteCode?: string | null
      isEnabled?: boolean
      successMessage: string
    }) => {
      const body: any = {
        courseId: courseData.course?.id,
      }
      if (params.inviteCode !== undefined) {
        body.courseInviteCode = params.inviteCode
      }
      if (params.isEnabled !== undefined) {
        body.isCourseInviteEnabled = params.isEnabled
      }

      await API.course
        .editCourseInfo(Number(courseData.course?.id), body)
        .then(() => {
          fetchCourseData()
          message.success(params.successMessage)
        })
        .catch((error) => {
          const errorMessage = getErrorMessage(error)
          message.error('Failed to update invite link: ' + errorMessage)
        })
    },
    [courseData.course?.id, fetchCourseData],
  )

  useEffect(() => {
    form.setFieldsValue({ courseInviteCode: courseCode ?? null })
  }, [courseCode, form])

  const handleEnableDisable = async () => {
    if (!isEnabled) {
      // Enabling: if no existing code, generate a new one
      if (!courseCode) {
        await updateCourseInvite({
          inviteCode: '',
          isEnabled: true,
          successMessage: 'Invite link enabled and generated',
        })
      } else {
        await updateCourseInvite({
          isEnabled: true,
          successMessage: 'Invite link enabled',
        })
      }
    } else {
      await updateCourseInvite({
        isEnabled: false,
        successMessage: 'Invite link disabled',
      })
    }
  }

  const handleRegenerate = async () => {
    await updateCourseInvite({
      inviteCode: '',
      isEnabled: true,
      successMessage: 'Invite link regenerated',
    })
  }

  const isHttps = window.location.protocol === 'https:'
  const baseURL = `${isHttps ? 'https' : 'http'}://${window.location.host}`
  const inviteURL =
    !courseCode || !isEnabled
      ? 'Invite link is disabled. No students can join the course'
      : `${baseURL}/invite?cid=${courseData.course?.id}&code=${encodeURIComponent(courseCode)}`

  const statusLabel = isEnabled
    ? 'Invite link is enabled'
    : 'Invite link is disabled'
  const statusColor = isEnabled ? 'bg-green-500' : 'bg-red-500'

  const handleCopy = () => {
    if (!courseCode || !isEnabled) {
      message.error('Invite link is disabled')
      return
    }
    navigator.clipboard.writeText(inviteURL).then(() => {
      setCopyLinkText('Copied!')
      setTimeout(() => {
        setCopyLinkText('Copy Link')
      }, 1000)
    })
  }

  return (
    <div className="space-y-3">
      <Form
        form={form}
        layout="vertical"
        initialValues={{
          courseInviteCode: courseCode,
        }}
        onFinish={() => {}}
      >
        <div className="mb-1 flex items-center gap-2">
          <span className={`h-2 w-2 rounded-full ${statusColor}`} />
          <span className="text-sm text-gray-700">{statusLabel}</span>
        </div>
        <Form.Item
          className="flex-1"
          label="Invite Code (read-only)"
          name="courseInviteCode"
          tooltip="This invite code is automatically generated by HelpMe and is only shown here for reference. Use the actions below to enable/disable or regenerate the invite link."
        >
          <Input allowClear={false} disabled />
        </Form.Item>
        <div className="mb-2 flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
          <div className="max-w-full break-all rounded border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-800">
            {inviteURL}
          </div>
          <div className="flex gap-2">
            <Button
              onClick={handleCopy}
              type="primary"
              size="small"
              disabled={!courseCode || !isEnabled}
              icon={<CopyOutlined />}
            >
              {copyLinkText}
            </Button>
            <Button
              onClick={() =>
                printQRCode(courseData.course?.name ?? '', inviteURL)
              }
              size="small"
              disabled={!courseCode || !isEnabled}
              icon={<QrcodeOutlined />}
            >
              Print QR Code
            </Button>
          </div>
        </div>
        <div className="flex w-full flex-wrap items-center justify-end gap-2 pt-1">
          <Button
            type={isEnabled ? 'default' : 'primary'}
            onClick={handleEnableDisable}
            className="px-4"
          >
            {isEnabled ? 'Disable Invite Link' : 'Enable Invite Link'}
          </Button>
          <Popconfirm
            title="Regenerate invite link?"
            description="This will invalidate the current invite link and generate a new one. Students with the old link will no longer be able to join."
            onConfirm={handleRegenerate}
            okText="Yes"
            cancelText="No"
          >
            <Button
              icon={<ReloadOutlined />}
              className="px-4"
              disabled={!isEnabled}
            >
              Regenerate Link
            </Button>
          </Popconfirm>
        </div>
      </Form>
    </div>
  )
}

export default CourseInviteCode
