CREATE DATABASE chatbot_test; GRANT ALL PRIVILEGES ON DATABASE chatbot_test TO helpme; ALTER DATABASE chatbot_test OWNER TO helpme;
CREATE DATABASE lti_test; GRANT ALL PRIVILEGES ON DATABASE lti_test TO helpme; ALTER DATABASE lti_test OWNER TO helpme;
CREATE DATABASE test; GRANT ALL PRIVILEGES ON DATABASE test TO helpme; ALTER DATABASE test OWNER TO helpme;